BearAlliance/pointing-poker

src/pages/game/game-page.jsx, src/pages/game/voting-buttons.jsx
=> feat: add points buttons

src/pages/game/game-page.jsx, src/pages/game/story-title-section.jsx
=> feat: add story title input

server/routes/games.js, server/routes/sockets.js, src/pages/game/add-player.jsx, src/pages/game/game-page.jsx, src/websocket-client.js
I think there is a better way to do this using routing, but I am not sure how yet.
I feel like I am recreating REST with a websocket, gotta read up on it
=> feat(add-player): move to websockets

src/pages/game/game-page.jsx, src/pages/game/game-stats.jsx, src/pages/game/players-table.jsx
Display Average/Min/Max points
=> Points info

server/routes/sockets.js, src/pages/game/game-page.jsx, src/pages/game/players-table.jsx, src/websocket-client.js
=> Voting reset

server/routes/sockets.js, src/pages/game/game-page.jsx, src/pages/game/story-title-section.jsx, src/websocket-client.js
=> feat: add shared editing of story title

src/App.scss, src/pages/game/game-page.jsx, src/pages/game/players-table.jsx
=> Obfuscate votes

server/routes/sockets.js, src/pages/game/game-page.jsx, src/pages/game/players-table.jsx, src/websocket-client.js
=> Show votes

server/routes/sockets.js, src/pages/game/add-player.jsx, src/pages/game/game-page.jsx, src/pages/game/game-title.jsx
=> feat: don't allow duplicate names fixes #10

server/routes/sockets.js, src/inputs/checkbox.jsx, src/pages/game/add-player.jsx, src/pages/game/game-page.jsx, src/pages/game/guests-table.jsx, src/pages/game/players-table.jsx, src/websocket-client.js
=> feat: allow player to join as guest

package-lock.json, package.json, server/routes/sockets.js
I might have a better way to do this, but this is functional
=> fix: remove disconnected players

src/pages/game/game-page.jsx, src/pages/game/game-stats.jsx, src/pages/game/players-table.jsx, src/pages/game/point-defender-info.jsx, src/pages/game/scorecard.jsx
=> feat: make stats visually distinct

src/App.jsx, src/pages/game/game-page.jsx, src/pages/game/game-title.jsx
=> fix: add fluid for mobile, reduce header size for small screens

src/pages/game/game-title.jsx
=> feat: add game link

src/pages/game/game-page.jsx, src/pages/game/game-title.jsx, src/pages/game/invite-link.jsx
=> feat: add lonley link

server/routes/sockets.js, src/websocket-client.js
heroku disconnects sockets after 30 seconds with no activity
Closes #47
=> fix: send heartbeat every 25 seconds

src/pages/game/voting-buttons.jsx
=> fix: don't allow someone to vote 0 points

server/routes/sockets.js, src/pages/game/point-defender-info.jsx
=> Dont rerender points defender so much

src/nav/nav.jsx, src/nav/new-game-button.jsx, src/pages/home/home-page.jsx
there isn't enough room in the nav bar on mobile
closes #50 
Desktop:
Mobile:
=> feat: add new and join buttons on the home page

README.md
=> docs: remove some boilerplate, add 'why' section

CODE_OF_CONDUCT.md
=> docs: create CODE_OF_CONDUCT

CONTRIBUTING.md
=> docs: create contribution guidelines

server/app.js, server/routes/game.js, server/routes/games.js, src/pages/home/games-in-progress.jsx, src/pages/home/home-page.jsx
=> feat: add games in progress count to home page

src/pages/home/count-up.jsx, src/pages/home/games-in-progress.jsx, src/pages/home/home-page.jsx
=> feat: add fun counting animation for games in progress

server/routes/game.js, server/routes/sockets.js, src/pages/game/active-game.jsx, src/pages/game/add-player.jsx, src/pages/game/game-page.jsx, src/websocket-client.js
it already worked for browser sesions, but we want to close the socket
when players stay on the site as well
closes #68
=> refactor: close socket when player leaves the route

.env, .eslintrc.js, .travis.yml, server/app.js, server/routes/sockets.js, src/nav/nav.jsx, src/pages/game/active-game.jsx
build the package when travis tests, because lint warnings become errors in ci with `create-react-app`
=> Lint build

src/pages/game/active-game.jsx
we don't want to abuse the danger color for normal actions
=> feat: make the 'clear votes' button warning color

src/pages/game/active-game.jsx, src/websocket-client.js
=> feat: add waring when socket is disconnected

server/routes/sockets.js
=> improvement: log socket close description

src/pages/game/game-stats.jsx, src/pages/game/voting-buttons.jsx
=> feat: allow voting with a ?

src/pages/game/voting-buttons.jsx
=> Fibonacci numbers, infinity

server/routes/sockets.js, src/pages/game/active-game.jsx, src/pages/game/add-player.jsx, src/pages/game/observer-switch.jsx, src/websocket-client.js
Also removes the clunky "join as observer" checkbox in the name screen
=> feat: allow player to become observer, and the reverse

server/routes/sockets.js, src/pages/game/active-game.jsx, src/websocket-client.js
=> feat: add toggle for showing votes

src/pages/retro/retro-item.jsx
=> feat(retro): improve retro item layout

package-lock.json, package.json, server/routes/poker-socket.js, server/routes/retro-socket.js, src/components/add-player.jsx, src/components/add-player.test.js, src/components/gravatar.jsx, src/contexts/participant-context.jsx, src/inputs/gravatar-input.jsx, src/pages/game/active-game.jsx, src/pages/game/game-page.jsx, src/pages/game/game-stats.jsx, src/pages/game/players-table.jsx, src/pages/retro/active-retro.jsx, src/pages/retro/retro-item.jsx, src/pages/retro/retro-page.jsx, src/pages/retro/retro-participants.jsx, src/websocket-client.js
=> feat: add gravatar icons

.eslintrc.js, package-lock.json, package.json, src/index.js
also add a lint rule to prevent this
=> fix: add runtime dependency to dependencies

src/pages/retro/retro-item.jsx
=> feat(retro): display liked by list for each item
